### ISSUE TITLE
Prevent automatic indexers non wanted change from schedule to save mode

### ISSUE THREAD

**Issue by jonathanribas** [pykettk/module-indexer-deploy-config#8]
Hi, 

Sometimes and we unfortunately don't know why, Adobe Commerce changes automatically indexers from schedule to save mode which causes huge performance imapcts.

Does locking indexers to schedule with this module will prevent automatic non wanted indexers change from schedule to save mode?

Thank in advance for your reply!

**Comment by pykettk** [comment]
Hi @jonathanribas 🙂 Sorry for the delayed response, I've only just seen this issue!

If Magento are using the indexer's `setScheduled()` function when this is happening then this module will prevent that. However if they are setting the value directly in the database then no. It's unfortunate that you don't know why this issue occurs else we could probably account for it here.

That being said, I've just had a thought for some additional functionality I can add that might (hopefully) make this a non-issue and cover a case that is potentially unaccounted for:
1. Creating a cron to query all indexer statuses and set them to the appropriate mode based on the deployment configuration should hopefully mean anything that slips through and manages to change the indexer mode (such as a direct database change) will only be functional for 1 minute at most
2. A plugin for the indexer's `setData()` function to check whether the mode is being changed when assigning values in bulk

I'll think more about this over the next couple of days and hopefully get something together over the weekend 🙂

**Comment by jonathanribas** [comment]
Hi @pykettk, in fact we don't know how to reproduce, unfortunately...
I think second option is more elegant, Adobe Commerce already run tons of cronjobs.

**Comment by pykettk** [comment]
I've implemented both of these solutions, @jonathanribas but have disabled the cron by default. You can find the full changelog in #9 🙂 Thanks again for the suggestion!

**Comment by jonathanribas** [comment]
Thank you @pykettk!
